import Navbar from '@/app/components/user/usersnavbar';
import Footer from '@/app/components/publicfooter';
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Inisialisasi font Inter
const inter = Inter({
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "BelanjaAja | Keranjang Saya",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    /* Kita gunakan inter.className langsung di sini. 
       Ini otomatis menerapkan font Inter ke semua elemen di dalamnya.
    */
    <div className={`${inter.className} antialiased min-h-screen flex flex-col bg-slate-50`}>
      <Navbar />
      <main className="flex-grow w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-2 pb-24 md:pb-10">
        {children}
      </main>
      <Footer />
    </div>
  );
}