import { ReactNode } from 'react'
import PublicNavbar from '@/app/components/publicnavbar'
import UserNavbar from '@/app/components/user/usersnavbar'
import Footer from '@/app/components/publicfooter'
import { getUserFromToken } from '@/lib/auth'
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Inisialisasi font Inter
const inter = Inter({
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "BelanjaAja | Keranjang Saya",
  description: "Generated by create next app",
};
export default async function Layout({
  children,
}: {
  children: ReactNode
}) {
  const user = await getUserFromToken()

  return (
    <div className={`${inter.className} antialiased min-h-screen flex flex-col bg-slate-50`}>

      {/* Auto Switch Navbar */}
      {user ? <UserNavbar /> : <PublicNavbar />}

      <main className="flex-grow w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-2 pb-24 md:pb-10">
        {children}
      </main>

      <Footer />
    </div>
  )
}
